name: ğŸš€ Deploy to CPanel

on:
  push:
    branches:
      - main  # Ubah ini dari 'ci/add-deploy-to-cpanel' menjadi 'main'

jobs:
  web-deploy:
    name: ğŸ‰ Sync Files
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
    - name: ğŸ› ï¸ Install dependencies
      run: npm install

    - name: ğŸ—ï¸ Build project
      run: npm run build
      uses: actions/checkout@v4

    - name: ğŸ“‚ Sync files to CPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.CPANEL_HOST }}
        username: ${{ secrets.CPANEL_USERNAME }}
        password: ${{ secrets.CPANEL_PASSWORD }}
        server-dir: ./public_html/appspb1/

