name: ðŸš€ Deploy to CPanel

on:
  push:
    branches:
      - main  # Memastikan jalan di branch main sesuai tampilan Anda

jobs:
  web-deploy:
    name: ðŸŽ‰ Sync Files
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v4

    - name: ðŸ“‚ Sync files to CPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.CPANEL_HOST }}
        username: ${{ secrets.CPANEL_USERNAME }}
        password: ${{ secrets.CPANEL_PASSWORD }}
        # Path ini disesuaikan dengan Repository Path di cPanel Anda
        server-dir: public_html/appspb1/
